import { IGetAidProps } from "@/actions/actor/common/aids-management/getAid";
import { IGetAidsProps } from "@/actions/actor/common/aids-management/getAids";
import { IAidResponse, IAidsResponse, TAid } from "@/types/actor/common/aids-management/aids-management.types";
import { QUANTITY_AVAILABILITY, TYPE_AIDS, DISTRIBUTION_MECHANISM, TYPE_GROUP_AIDS } from "@/types/actor/common/index.type";


export const fakeAids: TAid[] = [
    // Scenario 1: DELEGATES_LISTS, EQUAL distribution, FOOD_AID, ONGOING_AIDS
    {
        id: "1001",
        aidName: 'توزيع مواد غذائية',
        aidType: TYPE_AIDS.FOOD_AID,
        aidContent: 'حزم غذائية أساسية (أرز، زيت، دقيق)',
        deliveryDate: new Date('2025-08-15T09:00:00'),
        deliveryLocation: 'مخيم الشمال',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.LIMITED,
        existingQuantity: 200,
        selectedCategories: [
            { id: 'cat-1', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 4 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.DELEGATES_LISTS,
        selectedDisplacedIds: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        selectedDelegatesPortions: [
            { delegateId: '1', portion: 25 },
            { delegateId: '2', portion: 25 },
            { delegateId: '3', portion: 25 },
            { delegateId: '4', portion: 25 },
            { delegateId: '5', portion: 25 },
            { delegateId: '6', portion: 25 },
            { delegateId: '7', portion: 25 },
            { delegateId: '8', portion: 25 },
        ],
        receivedDisplaceds: [
            { displacedId: '1', receivedTime: new Date('2025-08-15T10:00:00') },
            { displacedId: '2', receivedTime: new Date('2025-08-15T10:30:00') },
        ],
        securitiesId: ['1', '2'], // Using delegate IDs for realism
        isCompleted: false,
        aidStatus: TYPE_GROUP_AIDS.ONGOING_AIDS,
        additionalNotes: 'توزيع في المخيم الرئيسي',
    },
    // Scenario 2: DELEGATES_LISTS, MANUAL distribution, MEDICAL_AID, COMING_AIDS
    {
        id: '1002',
        aidName: 'توزيع أدوية طبية',
        aidType: TYPE_AIDS.MEDICAL_AID,
        aidContent: 'أدوية للأمراض المزمنة',
        deliveryDate: new Date('2025-09-01T08:00:00'),
        deliveryLocation: 'مركز صحي الوسط',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.LIMITED,
        existingQuantity: 80,
        selectedCategories: [
            { id: 'مرضى', label: 'مرضى', min: 0, max: null, isDefault: true, portion: 1 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.DELEGATES_LISTS,
        selectedDisplacedIds: ['3', '4', '5', '6', '7', '8'],
        selectedDelegatesPortions: [
            { delegateId: '1', portion: 15 },
            { delegateId: '2', portion: 15 },
            { delegateId: '3', portion: 10 },
            { delegateId: '4', portion: 10 },
        ],
        receivedDisplaceds: [
            { displacedId: '3', receivedTime: new Date('2025-08-15T10:00:00') },
            { displacedId: '6', receivedTime: new Date('2025-08-15T10:30:00') },
        ],
        securitiesId: ['3', '4'],
        isCompleted: false,
        aidStatus: TYPE_GROUP_AIDS.COMING_AIDS,
        additionalNotes: 'يتطلب تخزين مبرد',
    },
    // Scenario 3: DISPLACED_FAMILIES, FAMILY_NUMBER, CLOTHING_AIDS, PREVIOUS_AIDS
    {
        id: '1003',
        aidName: 'توزيع ملابس شتوية',
        aidType: TYPE_AIDS.CLOTHING_AIDS,
        aidContent: 'معاطف وبطانيات شتوية',
        deliveryDate: new Date('2025-01-15T10:00:00'),
        deliveryLocation: 'مخيم الجنوب',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.LIMITED,
        existingQuantity: 150,
        selectedCategories: [
            { id: 'cat-3', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 3 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.DISPLACED_FAMILIES,
        selectedDisplacedIds: ['1', '2', '5', '6', '9', '10', '13', '14', '15', '16'],
        selectedDelegatesPortions: [],
        receivedDisplaceds: [
            { displacedId: '1', receivedTime: new Date('2025-01-15T11:00:00') },
            { displacedId: '2', receivedTime: new Date('2025-01-15T11:15:00') },
            { displacedId: '5', receivedTime: new Date('2025-01-15T11:30:00') },
        ],
        securitiesId: [],
        isCompleted: true,
        aidStatus: TYPE_GROUP_AIDS.PREVIOUS_AIDS,
        additionalNotes: 'توزيع مباشر للعائلات',
    },
    // Scenario 4: DELEGATES_LISTS, EQUAL, WATER_AID, ONGOING_AIDS
    {
        id: '1004',
        aidName: 'توزيع مياه معبأة',
        aidType: TYPE_AIDS.OTHER_AID,
        aidContent: 'عبوات مياه للشرب',
        deliveryDate: new Date('2025-07-28T11:00:00'),
        deliveryLocation: 'مخيم الشرق',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.UNLIMITED,
        existingQuantity: 500,
        selectedCategories: [
            { id: 'cat-4', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 6 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.DELEGATES_LISTS,
        selectedDisplacedIds: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],
        selectedDelegatesPortions: [
            { delegateId: '1', portion: 60 },
            { delegateId: '2', portion: 60 },
            { delegateId: '3', portion: 60 },
            { delegateId: '4', portion: 60 },
            { delegateId: '5', portion: 60 },
        ],
        receivedDisplaceds: [
            { displacedId: '1', receivedTime: new Date('2025-07-28T12:00:00') },
            { displacedId: '2', receivedTime: new Date('2025-07-28T12:10:00') },
        ],
        securitiesId: ['5', '6'],
        isCompleted: false,
        aidStatus: TYPE_GROUP_AIDS.ONGOING_AIDS,
        additionalNotes: 'أولوية عالية للمياه النظيفة',
    },
    // Scenario 5: DISPLACED_FAMILIES, EQUAL, EDUCATIONAL_AID, COMING_AIDS
    {
        id: '1005',
        aidName: 'توزيع كتب دراسية',
        aidType: TYPE_AIDS.EDUCATIONAL_AID,
        aidContent: 'كتب مدرسية للأطفال',
        deliveryDate: new Date('2025-09-10T09:00:00'),
        deliveryLocation: 'مدرسة المخيم',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.LIMITED,
        existingQuantity: 200,
        selectedCategories: [
            { id: 'cat-5', label: 'طلاب', min: 6, max: 18, isDefault: true, portion: 5 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.DISPLACED_FAMILIES,
        selectedDisplacedIds: ['5', '6', '9', '10', '13', '14', '15', '16'],
        receivedDisplaceds: [],
        securitiesId: [],
        isCompleted: false,
        aidStatus: TYPE_GROUP_AIDS.COMING_AIDS,
        additionalNotes: 'للطلاب في المدارس الابتدائية',
    },
    // Scenario 6: DELEGATES_LISTS, MANUAL, CLEANING_AID, PREVIOUS_AIDS
    {
        id: '1006',
        aidName: 'توزيع مستلزمات تنظيف',
        aidType: TYPE_AIDS.CLEANING_AID,
        aidContent: 'صابون ومعقمات',
        deliveryDate: new Date('2025-02-01T11:00:00'),
        deliveryLocation: 'مخيم الغرب',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.LIMITED,
        existingQuantity: 300,
        selectedCategories: [
            { id: 'cat-6', label: 'عائلات صغيرة', min: 1, max: 4, isDefault: true, portion: 4 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.DELEGATES_LISTS,
        selectedDisplacedIds: ['1', '2', '7', '8', '11', '12', '17', '18'],
        selectedDelegatesPortions: [
            { delegateId: '1', portion: 50 },
            { delegateId: '2', portion: 50 },
            { delegateId: '3', portion: 40 },
            { delegateId: '4', portion: 40 },
        ],
        receivedDisplaceds: [
            { displacedId: '1', receivedTime: new Date('2025-02-01T12:00:00') },
            { displacedId: '2', receivedTime: new Date('2025-02-01T12:15:00') },
            { displacedId: '7', receivedTime: new Date('2025-02-01T12:30:00') },
            { displacedId: '8', receivedTime: new Date('2025-02-01T12:45:00') },
        ],
        securitiesId: [],
        isCompleted: true,
        aidStatus: TYPE_GROUP_AIDS.PREVIOUS_AIDS,
        additionalNotes: 'توزيع للعائلات الصغيرة',
    },
    // Scenario 7: DISPLACED_FAMILIES, FAMILY_NUMBER, FINANCIAL_AID, ONGOING_AIDS
    {
        id: '1007',
        aidName: 'توزيع مساعدات مالية',
        aidType: TYPE_AIDS.FINANCIAL_AID,
        aidContent: 'دعم مالي للعائلات المتضررة',
        deliveryDate: new Date('2025-07-28T12:00:00'),
        deliveryLocation: 'مركز الدفع المالي',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.LIMITED,
        existingQuantity: 1000,
        selectedCategories: [
            { id: 'cat-7', label: 'عائلات فقيرة', min: 1, max: null, isDefault: true, portion: 50 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.DISPLACED_FAMILIES,
        selectedDisplacedIds: ['3', '4', '9', '10', '13', '14', '15', '16', '19', '20'],
        receivedDisplaceds: [
            { displacedId: '3', receivedTime: new Date('2025-07-28T13:00:00') },
            { displacedId: '4', receivedTime: new Date('2025-07-28T13:10:00') },
        ],
        securitiesId: ['7', '8'],
        isCompleted: false,
        aidStatus: TYPE_GROUP_AIDS.ONGOING_AIDS,
        additionalNotes: 'توزيع نقدي آمن',
    },
    // Scenario 8: DELEGATES_LISTS, EQUAL, OTHER_AID (Tents), COMING_AIDS
    {
        id: '1008',
        aidName: 'توزيع خيام',
        aidType: TYPE_AIDS.OTHER_AID,
        aidContent: 'خيام للإيواء المؤقت',
        deliveryDate: new Date('2025-10-01T10:00:00'),
        deliveryLocation: 'مخيم الشرق',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.LIMITED,
        existingQuantity: 50,
        selectedCategories: [
            { id: 'cat-8', label: 'عائلات متضررة', min: 1, max: null, isDefault: true, portion: 1 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.DELEGATES_LISTS,
        selectedDisplacedIds: ['1', '2', '3', '4', '5', '6'],
        selectedDelegatesPortions: [
            { delegateId: '1', portion: 6 },
            { delegateId: '2', portion: 6 },
            { delegateId: '3', portion: 6 },
            { delegateId: '4', portion: 6 },
        ],
        receivedDisplaceds: [],
        securitiesId: ["1", "2"],
        isCompleted: false,
        aidStatus: TYPE_GROUP_AIDS.COMING_AIDS,
        additionalNotes: 'خيام مقاومة للماء',
    },
    // Scenario 9: DISPLACED_FAMILIES, EQUAL, FOOD_AID, PREVIOUS_AIDS
    {
        id: '1009',
        aidName: 'توزيع حزم غذائية طارئة',
        aidType: TYPE_AIDS.FOOD_AID,
        aidContent: 'مواد غذائية متنوعة',
        deliveryDate: new Date('2025-03-01T09:00:00'),
        deliveryLocation: 'مخيم الغرب',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.LIMITED,
        existingQuantity: 180,
        selectedCategories: [
            { id: 'cat-9', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 5 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.DISPLACED_FAMILIES,
        selectedDisplacedIds: ['7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18'],
        receivedDisplaceds: [
            { displacedId: '7', receivedTime: new Date('2025-03-01T10:00:00') },
            { displacedId: '8', receivedTime: new Date('2025-03-01T10:15:00') },
            { displacedId: '9', receivedTime: new Date('2025-03-01T10:30:00') },
        ],
        securitiesId: ['3', '4'],
        isCompleted: true,
        aidStatus: TYPE_GROUP_AIDS.PREVIOUS_AIDS,
        additionalNotes: 'توزيع طارئ',
    },
    // Scenario 10: DELEGATES_LISTS, MANUAL, EDUCATIONAL_AID, ONGOING_AIDS
    {
        id: '1010',
        aidName: 'توزيع لوازم مدرسية',
        aidType: TYPE_AIDS.EDUCATIONAL_AID,
        aidContent: 'حقائب وأدوات مدرسية',
        deliveryDate: new Date('2025-08-01T09:00:00'),
        deliveryLocation: 'مدرسة الشمال',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.LIMITED,
        existingQuantity: 150,
        selectedCategories: [
            { id: 'cat-10', label: 'طلاب', min: 6, max: 18, isDefault: true, portion: 4 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.DELEGATES_LISTS,
        selectedDisplacedIds: ['5', '6', '9', '10', '13', '14'],
        selectedDelegatesPortions: [
            { delegateId: '5', portion: 30 },
            { delegateId: '6', portion: 30 },
            { delegateId: '7', portion: 20 },
            { delegateId: '8', portion: 20 },
        ],
        receivedDisplaceds: [
            { displacedId: '5', receivedTime: new Date('2025-08-01T10:00:00') },
            { displacedId: '6', receivedTime: new Date('2025-08-01T10:15:00') },
        ],
        securitiesId: [],
        isCompleted: false,
        aidStatus: TYPE_GROUP_AIDS.ONGOING_AIDS,
        additionalNotes: 'للطلاب في المدارس الابتدائية',
    },
    // Scenario 11: DISPLACED_FAMILIES, FAMILY_NUMBER, CLEANING_AID, COMING_AIDS
    {
        id: '1011',
        aidName: 'توزيع مستلزمات النظافة',
        aidType: TYPE_AIDS.CLEANING_AID,
        aidContent: 'صابون وشامبو ومنظفات',
        deliveryDate: new Date('2025-10-15T11:00:00'),
        deliveryLocation: 'مخيم الجنوب',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.UNLIMITED,
        existingQuantity: 400,
        selectedCategories: [
            { id: 'cat-11', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 4 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.DISPLACED_FAMILIES,
        selectedDisplacedIds: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],
        receivedDisplaceds: [],
        securitiesId: [],
        isCompleted: false,
        aidStatus: TYPE_GROUP_AIDS.COMING_AIDS,
        additionalNotes: 'توزيع شامل للنظافة',
    },
    // Scenario 12: DELEGATES_LISTS, EQUAL, MEDICAL_AID, PREVIOUS_AIDS
    {
        id: '1012',
        aidName: 'توزيع معدات طبية',
        aidType: TYPE_AIDS.MEDICAL_AID,
        aidContent: 'معدات إسعاف أولي',
        deliveryDate: new Date('2025-04-01T08:00:00'),
        deliveryLocation: 'مركز صحي الغرب',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.LIMITED,
        existingQuantity: 60,
        selectedCategories: [
            { id: 'cat-12', label: 'مراكز صحية', min: 0, max: null, isDefault: true, portion: 1 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.DELEGATES_LISTS,
        selectedDisplacedIds: ['9', '10', '11', '12', '13', '14'],
        selectedDelegatesPortions: [
            { delegateId: '1', portion: 7 },
            { delegateId: '2', portion: 7 },
            { delegateId: '3', portion: 7 },
            { delegateId: '4', portion: 7 },
        ],
        receivedDisplaceds: [
            { displacedId: '9', receivedTime: new Date('2025-04-01T09:00:00') },
            { displacedId: '10', receivedTime: new Date('2025-04-01T09:15:00') },
        ],
        securitiesId: ['5', '6'],
        isCompleted: true,
        aidStatus: TYPE_GROUP_AIDS.PREVIOUS_AIDS,
        additionalNotes: 'توزيع للمراكز الصحية',
    },
    // Scenario 13: DISPLACED_FAMILIES, EQUAL, WATER_AID, ONGOING_AIDS
    {
        id: '1013',
        aidName: 'توزيع مياه معبأة إضافية',
        aidType: TYPE_AIDS.OTHER_AID,
        aidContent: 'عبوات مياه للشرب',
        deliveryDate: new Date('2025-07-28T10:00:00'),
        deliveryLocation: 'مخيم الشمال',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.UNLIMITED,
        existingQuantity: 600,
        selectedCategories: [
            { id: 'cat-13', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 6 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.DISPLACED_FAMILIES,
        selectedDisplacedIds: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16'],
        receivedDisplaceds: [
            { displacedId: '1', receivedTime: new Date('2025-07-28T11:00:00') },
            { displacedId: '2', receivedTime: new Date('2025-07-28T11:10:00') },
            { displacedId: '3', receivedTime: new Date('2025-07-28T11:20:00') },
        ],
        securitiesId: ['7', '8'],
        isCompleted: false,
        aidStatus: TYPE_GROUP_AIDS.ONGOING_AIDS,
        additionalNotes: 'توزيع مياه طارئ',
    },
    // Scenario 14: DELEGATES_LISTS, MANUAL, CLOTHING_AIDS, COMING_AIDS
    {
        id: '1014',
        aidName: 'توزيع ملابس صيفية',
        aidType: TYPE_AIDS.CLOTHING_AIDS,
        aidContent: 'ملابس خفيفة للأطفال',
        deliveryDate: new Date('2025-11-01T10:00:00'),
        deliveryLocation: 'مخيم الشرق',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.LIMITED,
        existingQuantity: 200,
        selectedCategories: [
            { id: 'cat-14', label: 'أطفال', min: 0, max: 12, isDefault: true, portion: 3 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.DELEGATES_LISTS,
        selectedDisplacedIds: ['5', '6', '9', '10', '13', '14'],
        selectedDelegatesPortions: [
            { delegateId: '1', portion: 40 },
            { delegateId: '2', portion: 40 },
            { delegateId: '3', portion: 30 },
            { delegateId: '4', portion: 30 },
        ],
        receivedDisplaceds: [],
        securitiesId: [],
        isCompleted: false,
        aidStatus: TYPE_GROUP_AIDS.COMING_AIDS,
        additionalNotes: 'للأطفال دون 12 سنة',
    },
    // Scenario 15: DISPLACED_FAMILIES, FAMILY_NUMBER, OTHER_AID (Tents), PREVIOUS_AIDS
    {
        id: '1015',
        aidName: 'توزيع خيام إضافية',
        aidType: TYPE_AIDS.OTHER_AID,
        aidContent: 'خيام للإيواء المؤقت',
        deliveryDate: new Date('2025-05-01T10:00:00'),
        deliveryLocation: 'مخيم الغرب',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.LIMITED,
        existingQuantity: 40,
        selectedCategories: [
            { id: 'cat-15', label: 'عائلات متضررة', min: 1, max: null, isDefault: true, portion: 1 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.DISPLACED_FAMILIES,
        selectedDisplacedIds: ['1', '2', '3', '4', '5', '6', '7', '8'],
        receivedDisplaceds: [
            { displacedId: '1', receivedTime: new Date('2025-05-01T11:00:00') },
            { displacedId: '2', receivedTime: new Date('2025-05-01T11:15:00') },
            { displacedId: '3', receivedTime: new Date('2025-05-01T11:30:00') },
            { displacedId: '4', receivedTime: new Date('2025-05-01T11:45:00') },
        ],
        securitiesId: ['1', '2'],
        isCompleted: true,
        aidStatus: TYPE_GROUP_AIDS.PREVIOUS_AIDS,
        additionalNotes: 'خيام مقاومة للرياح',
    },
    // Scenario 16: DELEGATES_LISTS, EQUAL, FINANCIAL_AID, ONGOING_AIDS
    {
        id: '1016',
        aidName: 'توزيع مساعدات مالية إضافية',
        aidType: TYPE_AIDS.FINANCIAL_AID,
        aidContent: 'دعم مالي للعائلات الكبيرة',
        deliveryDate: new Date('2025-07-28T12:00:00'),
        deliveryLocation: 'مركز الدفع المالي',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.LIMITED,
        existingQuantity: 800,
        selectedCategories: [
            { id: 'cat-16', label: 'عائلات كبيرة', min: 5, max: null, isDefault: true, portion: 50 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.DELEGATES_LISTS,
        selectedDisplacedIds: ['5', '6', '9', '10', '13', '14', '15', '16'],
        selectedDelegatesPortions: [
            { delegateId: '1', portion: 100 },
            { delegateId: '2', portion: 100 },
            { delegateId: '3', portion: 100 },
            { delegateId: '4', portion: 100 },
        ],
        receivedDisplaceds: [
            { displacedId: '5', receivedTime: new Date('2025-07-28T13:00:00') },
            { displacedId: '6', receivedTime: new Date('2025-07-28T13:15:00') },
        ],
        securitiesId: ['5', '6'],
        isCompleted: false,
        aidStatus: TYPE_GROUP_AIDS.ONGOING_AIDS,
        additionalNotes: 'توزيع نقدي آمن',
    },
    // Scenario 17: DISPLACED_FAMILIES, EQUAL, MEDICAL_AID, COMING_AIDS
    {
        id: '1017',
        aidName: 'توزيع مستلزمات صحية',
        aidType: TYPE_AIDS.MEDICAL_AID,
        aidContent: 'معدات صحية للعناية',
        deliveryDate: new Date('2025-11-15T08:00:00'),
        deliveryLocation: 'مركز صحي الجنوب',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.LIMITED,
        existingQuantity: 70,
        selectedCategories: [
            { id: 'cat-17', label: 'مراكز صحية', min: 0, max: null, isDefault: true, portion: 1 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.DISPLACED_FAMILIES,
        selectedDisplacedIds: ['9', '10', '11', '12', '13', '14', '15', '16', '19', '20'],
        receivedDisplaceds: [],
        securitiesId: ['7', '8'],
        isCompleted: false,
        aidStatus: TYPE_GROUP_AIDS.COMING_AIDS,
        additionalNotes: 'للمراكز الصحية',
    },
    // Scenario 18: DELEGATES_LISTS, MANUAL, WATER_AID, PREVIOUS_AIDS
    {
        id: '1018',
        aidName: 'توزيع مياه إضافية',
        aidType: TYPE_AIDS.OTHER_AID,
        aidContent: 'عبوات مياه للشرب',
        deliveryDate: new Date('2025-06-01T11:00:00'),
        deliveryLocation: 'مخيم الغرب',
        securityRequired: true,
        quantityAvailability: QUANTITY_AVAILABILITY.UNLIMITED,
        existingQuantity: 500,
        selectedCategories: [
            { id: 'cat-18', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 6 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.DELEGATES_LISTS,
        selectedDisplacedIds: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        selectedDelegatesPortions: [
            { delegateId: '1', portion: 60 },
            { delegateId: '2', portion: 60 },
            { delegateId: '3', portion: 50 },
            { delegateId: '4', portion: 50 },
        ],
        receivedDisplaceds: [
            { displacedId: '1', receivedTime: new Date('2025-06-01T12:00:00') },
            { displacedId: '2', receivedTime: new Date('2025-06-01T12:15:00') },
            { displacedId: '3', receivedTime: new Date('2025-06-01T12:30:00') },
        ],
        securitiesId: ['1', '2'],
        isCompleted: true,
        aidStatus: TYPE_GROUP_AIDS.PREVIOUS_AIDS,
        additionalNotes: 'توزيع مياه طارئ',
    },
    // Scenario 19: DISPLACED_FAMILIES, FAMILY_NUMBER, CLOTHING_AIDS, ONGOING_AIDS
    {
        id: '1019',
        aidName: 'توزيع أغطية شتوية',
        aidType: TYPE_AIDS.CLOTHING_AIDS,
        aidContent: 'بطانيات دافئة',
        deliveryDate: new Date('2025-07-28T10:00:00'),
        deliveryLocation: 'مخيم الجنوب',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.LIMITED,
        existingQuantity: 120,
        selectedCategories: [
            { id: 'cat-19', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 2 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.DISPLACED_FAMILIES,
        selectedDisplacedIds: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        receivedDisplaceds: [
            { displacedId: '1', receivedTime: new Date('2025-07-28T11:00:00') },
            { displacedId: '2', receivedTime: new Date('2025-07-28T11:15:00') },
        ],
        securitiesId: [],
        isCompleted: false,
        aidStatus: TYPE_GROUP_AIDS.ONGOING_AIDS,
        additionalNotes: 'توزيع للعائلات',
    },
    // Scenario 20: DELEGATES_LISTS, EQUAL, OTHER_AID (Kitchen Equipment), COMING_AIDS
    {
        id: '1020',
        aidName: 'توزيع معدات مطبخ',
        aidType: TYPE_AIDS.OTHER_AID,
        aidContent: 'أدوات طهي للعائلات',
        deliveryDate: new Date('2025-12-01T10:00:00'),
        deliveryLocation: 'مخيم الشمال',
        securityRequired: false,
        quantityAvailability: QUANTITY_AVAILABILITY.LIMITED,
        existingQuantity: 100,
        selectedCategories: [
            { id: 'cat-20', label: 'عائلات', min: 1, max: null, isDefault: true, portion: 3 },
        ],
        distributionMechanism: DISTRIBUTION_MECHANISM.DELEGATES_LISTS,
        selectedDisplacedIds: ['1', '2', '3', '4', '5', '6', '7', '8'],
        selectedDelegatesPortions: [
            { delegateId: '1', portion: 12 },
            { delegateId: '2', portion: 12 },
            { delegateId: '3', portion: 12 },
            { delegateId: '4', portion: 12 },
        ],
        receivedDisplaceds: [],
        securitiesId: [],
        isCompleted: false,
        aidStatus: TYPE_GROUP_AIDS.COMING_AIDS,
        additionalNotes: 'توزيع للعائلات',
    },
];

export function fakeAidResponse({
    aidId
}: IGetAidProps): IAidResponse {
    const filteredAid = fakeAids.find(aid => aid.id === aidId)

    return {
        status: 200,
        message: 'تم جلب المساعدة بنجاح',
        aid: filteredAid as TAid,
    };
}

export function fakeAidsResponse({
    page,
    limit,
    aidStatus,
}: IGetAidsProps): IAidsResponse {
    const filteredAids = aidStatus
        ? fakeAids.filter(aid => aid.aidStatus === aidStatus)
        : fakeAids;

    const start = (page - 1) * limit;
    const end = start + limit;
    const paginatedAids = filteredAids.slice(start, end);

    return {
        status: 200,
        message: 'تم جلب المساعدات بنجاح',
        aids: paginatedAids,
        pagination: {
            page,
            limit,
            totalItems: filteredAids.length,
            totalPages: Math.ceil(filteredAids.length / limit),
        },
    };
}