export enum DESTINATION_HERO_SECTION {
    HOME = 'HOME',
    BLOG = 'BLOG',
    SUCCESS_STORIES = 'SUCCESS_STORIES',
}

export enum TYPE_WRITTEN_CONTENT {
    BLOG = 'BLOG',
    SUCCESS_STORIES = 'SUCCESS_STORIES',
}
