import IMG_SUCCESS_STORY_HERO_SLIDER_1 from './hero-slider-1.jpg';
import IMG_SUCCESS_STORY_HERO_SLIDER_2 from './hero-slider-2.jpg';
import IMG_SUCCESS_STORY_HERO_SLIDER_3 from './hero-slider-3.jpg';
import IMG_SUCCESS_STORY_HERO_SLIDER_4 from './hero-slider-4.jpg';

export {
  IMG_SUCCESS_STORY_HERO_SLIDER_1,
  IMG_SUCCESS_STORY_HERO_SLIDER_2,
  IMG_SUCCESS_STORY_HERO_SLIDER_3,
  IMG_SUCCESS_STORY_HERO_SLIDER_4,
};
