import { GENDER, SOCIAL_STATUS } from "@/types/actor/common/index.type";
import { IDelegateProfile, IDelegateProfileResponse } from "@/types/actor/delegates/profile/delegate-profile-response.type";

export const fakeDelegateProfiles: IDelegateProfile[] = [
  {
    id: -1,
    name: "بدون مندوب",
    profileImage: "",
    identity: "960128155",
    gender: GENDER.MALE,
    socialStatus: SOCIAL_STATUS.SINGLE,
    email: "no_delegate@example.com",
    age: 0,
    education: "غير محدد",
    mobileNumber: "0595000000",
    alternativeMobileNumber: undefined,
    numberOfResponsibleCamps: 0,
    numberOfFamilies: 0,
    nationality: "",
  },
  {
    id: 1,
    name: "mostafa aljzar",
    profileImage: null,
    identity: "408656429",
    gender: GENDER.MALE,
    socialStatus: SOCIAL_STATUS.MARRIED,
    email: "mostafaibrahim20032020@gmail.com",
    age: 35,
    education: "بكالوريوس إدارة أعمال",
    mobileNumber: "0595867456",
    alternativeMobileNumber: "0591234567",
    numberOfResponsibleCamps: 10,
    numberOfFamilies: 20,
    nationality: "فلسطيني",
  },
  {
    id: 2,
    name: "علي خالد بن عمر",
    profileImage: null,
    identity: "960128156",
    gender: GENDER.MALE,
    socialStatus: SOCIAL_STATUS.MARRIED,
    email: "ali.khalid@example.com",
    age: 40,
    education: "دبلوم هندسة مدنية",
    mobileNumber: "0595867457",
    alternativeMobileNumber: "0591234568",
    numberOfResponsibleCamps: 12,
    numberOfFamilies: 25,
    nationality: "فلسطيني",
  },
  {
    id: 3,
    name: "فاطمة زيد بنت حسن",
    profileImage: null,
    identity: "960128157",
    gender: GENDER.FEMALE,
    socialStatus: SOCIAL_STATUS.SINGLE,
    email: "fatima.zeid@example.com",
    age: 28,
    education: "بكالوريوس تربية",
    mobileNumber: "0595867458",
    alternativeMobileNumber: undefined,
    numberOfResponsibleCamps: 8,
    numberOfFamilies: 18,
    nationality: "فلسطيني",
  },
  {
    id: 4,
    name: "خالد يوسف بن سالم",
    profileImage: null,
    identity: "960128158",
    gender: GENDER.MALE,
    socialStatus: SOCIAL_STATUS.DIVORCED,
    email: "khalid.yousuf@example.com",
    age: 45,
    education: "ماجستير إدارة",
    mobileNumber: "0595867459",
    alternativeMobileNumber: "0591234569",
    numberOfResponsibleCamps: 11,
    numberOfFamilies: 22,
    nationality: "فلسطيني",
  },
  {
    id: 5,
    name: "سارة ناصر بنت أحمد",
    profileImage: null,
    identity: "960128159",
    gender: GENDER.FEMALE,
    socialStatus: SOCIAL_STATUS.MARRIED,
    email: "sarah.nasser@example.com",
    age: 32,
    education: "بكالوريوس علوم",
    mobileNumber: "0595867460",
    alternativeMobileNumber: undefined,
    numberOfResponsibleCamps: 9,
    numberOfFamilies: 19,
    nationality: "فلسطيني",
  },
  {
    id: 6,
    name: "عمر زياد بن محمود",
    profileImage: null,
    identity: "960128160",
    gender: GENDER.MALE,
    socialStatus: SOCIAL_STATUS.SINGLE,
    email: "omar.ziyad@example.com",
    age: 29,
    education: "بكالوريوس تكنولوجيا معلومات",
    mobileNumber: "0595867461",
    alternativeMobileNumber: "0591234570",
    numberOfResponsibleCamps: 13,
    numberOfFamilies: 26,
    nationality: "فلسطيني",
  },
  {
    id: 7,
    name: "ليلى صبري بنت رامي",
    profileImage: null,
    identity: "960128161",
    gender: GENDER.FEMALE,
    socialStatus: SOCIAL_STATUS.WIDOWED,
    email: "layla.sabri@example.com",
    age: 38,
    education: "دبلوم تمريض",
    mobileNumber: "0595867462",
    alternativeMobileNumber: undefined,
    numberOfResponsibleCamps: 10,
    numberOfFamilies: 21,
    nationality: "فلسطيني",
  },
  {
    id: 8,
    name: "ياسر حمد بن عبدالله",
    profileImage: null,
    identity: "960128162",
    gender: GENDER.MALE,
    socialStatus: SOCIAL_STATUS.MARRIED,
    email: "yasser.hamad@example.com",
    age: 42,
    education: "بكالوريوس هندسة",
    mobileNumber: "0595867463",
    alternativeMobileNumber: "0591234571",
    numberOfResponsibleCamps: 11,
    numberOfFamilies: 23,
    nationality: "فلسطيني",
  },
]

export const fakeDelegateProfileResponse = ({
  delegateId,
}: {
  delegateId: number
}): IDelegateProfileResponse => {
  const delegateProfile = fakeDelegateProfiles.find(
    (profile) => profile.id === Number(delegateId)
  )

  if (!delegateProfile) {
    return {
      status: 404,
      message: "المندوب غير موجود",
      user: {} as IDelegateProfile,
      error: "Delegate not found",
    }
  }

  return {
    status: 200,
    message: "تم جلب بيانات الملف الشخصي بنجاح",
    user: delegateProfile,
    error: undefined,
  }
}
